name: Native

on:
  create:
    branches: [ master ]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  gradle:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set Main Host
        run: echo "isMainHost=false" >> $GITHUB_ENV
      - uses: actions/checkout@v1
      - run: sudo apt-get update --fix-missing && sudo apt-get install libcurl4-openssl-dev
        name: Install libcurl-dev
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Build files
        uses: actions/cache@v2
        if: ${{ !startsWith(matrix.os, 'windows') }}
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}
      - uses: eskatos/gradle-command-action@v1
        name: Test Windows Target
        if: ${{ startsWith(matrix.os, 'windows') }}
        with:
          arguments: win64Test
      - uses: eskatos/gradle-command-action@v1
        name: Test Apple Targets
        if: ${{ startsWith(matrix.os, 'macos') }}
        with:
          arguments: macosTest # iosTest tvosTest watchosX86Test
      - uses: eskatos/gradle-command-action@v1
        name: Test Linux Target
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        with:
          arguments: linuxX64Test
      - uses: eskatos/gradle-command-action@v1
        name: Publish Tag
        with:
          arguments: publish -Pversion=$GITHUB_REF
        if: ${{ startsWith(github.ref, 'refs/tags') }}
      - uses: eskatos/gradle-command-action@v1
        name: Publish SNAPSHOT
        with:
          arguments: publish
        if: ${{ startsWith(github.ref, 'refs/heads/master') }}
